/* This file is auto-generated by scripts/generateTypes.ts */
import type { Node } from './ast.js'

/** The tag of every possible node. */
export type NodeTag<TNode extends Node = Node> = TNode extends any
  ? keyof TNode
  : never

/** The type of a node by its tag. */
export type NodeByTag<TNodeTag extends NodeTag> = Node extends infer TNode
  ? TNode extends any
    ? TNodeTag extends keyof TNode
      ? TNode[TNodeTag]
      : never
    : never
  : never

export class NodePath<TNodeTag extends NodeTag = NodeTag> {
  constructor(
    readonly tag: TNodeTag,
    readonly node: NodeByTag<TNodeTag>,
    readonly parent: NodePath | null,
    readonly keyPath: readonly (string | number)[],
  ) {}
  isList(): this is NodePath<'List'> {
    return this.tag === 'List'
  }
  isRangeVar(): this is NodePath<'RangeVar'> {
    return this.tag === 'RangeVar'
  }
  isGroupingFunc(): this is NodePath<'GroupingFunc'> {
    return this.tag === 'GroupingFunc'
  }
  isNamedArgExpr(): this is NodePath<'NamedArgExpr'> {
    return this.tag === 'NamedArgExpr'
  }
  isDistinctExpr(): this is NodePath<'DistinctExpr'> {
    return this.tag === 'DistinctExpr'
  }
  isNullIfExpr(): this is NodePath<'NullIfExpr'> {
    return this.tag === 'NullIfExpr'
  }
  isBoolExpr(): this is NodePath<'BoolExpr'> {
    return this.tag === 'BoolExpr'
  }
  isSubLink(): this is NodePath<'SubLink'> {
    return this.tag === 'SubLink'
  }
  isCaseExpr(): this is NodePath<'CaseExpr'> {
    return this.tag === 'CaseExpr'
  }
  isCaseWhen(): this is NodePath<'CaseWhen'> {
    return this.tag === 'CaseWhen'
  }
  isRowExpr(): this is NodePath<'RowExpr'> {
    return this.tag === 'RowExpr'
  }
  isCoalesceExpr(): this is NodePath<'CoalesceExpr'> {
    return this.tag === 'CoalesceExpr'
  }
  isMinMaxExpr(): this is NodePath<'MinMaxExpr'> {
    return this.tag === 'MinMaxExpr'
  }
  isSQLValueFunction(): this is NodePath<'SQLValueFunction'> {
    return this.tag === 'SQLValueFunction'
  }
  isXmlExpr(): this is NodePath<'XmlExpr'> {
    return this.tag === 'XmlExpr'
  }
  isJsonValueExpr(): this is NodePath<'JsonValueExpr'> {
    return this.tag === 'JsonValueExpr'
  }
  isJsonIsPredicate(): this is NodePath<'JsonIsPredicate'> {
    return this.tag === 'JsonIsPredicate'
  }
  isNullTest(): this is NodePath<'NullTest'> {
    return this.tag === 'NullTest'
  }
  isBooleanTest(): this is NodePath<'BooleanTest'> {
    return this.tag === 'BooleanTest'
  }
  isSetToDefault(): this is NodePath<'SetToDefault'> {
    return this.tag === 'SetToDefault'
  }
  isCurrentOfExpr(): this is NodePath<'CurrentOfExpr'> {
    return this.tag === 'CurrentOfExpr'
  }
  isJoinExpr(): this is NodePath<'JoinExpr'> {
    return this.tag === 'JoinExpr'
  }
  isTypeName(): this is NodePath<'TypeName'> {
    return this.tag === 'TypeName'
  }
  isColumnRef(): this is NodePath<'ColumnRef'> {
    return this.tag === 'ColumnRef'
  }
  isParamRef(): this is NodePath<'ParamRef'> {
    return this.tag === 'ParamRef'
  }
  isA_Expr(): this is NodePath<'A_Expr'> {
    return this.tag === 'A_Expr'
  }
  isA_Const(): this is NodePath<'A_Const'> {
    return this.tag === 'A_Const'
  }
  isTypeCast(): this is NodePath<'TypeCast'> {
    return this.tag === 'TypeCast'
  }
  isCollateClause(): this is NodePath<'CollateClause'> {
    return this.tag === 'CollateClause'
  }
  isRoleSpec(): this is NodePath<'RoleSpec'> {
    return this.tag === 'RoleSpec'
  }
  isFuncCall(): this is NodePath<'FuncCall'> {
    return this.tag === 'FuncCall'
  }
  isA_Star(): this is NodePath<'A_Star'> {
    return this.tag === 'A_Star'
  }
  isA_Indices(): this is NodePath<'A_Indices'> {
    return this.tag === 'A_Indices'
  }
  isA_Indirection(): this is NodePath<'A_Indirection'> {
    return this.tag === 'A_Indirection'
  }
  isA_ArrayExpr(): this is NodePath<'A_ArrayExpr'> {
    return this.tag === 'A_ArrayExpr'
  }
  isResTarget(): this is NodePath<'ResTarget'> {
    return this.tag === 'ResTarget'
  }
  isMultiAssignRef(): this is NodePath<'MultiAssignRef'> {
    return this.tag === 'MultiAssignRef'
  }
  isSortBy(): this is NodePath<'SortBy'> {
    return this.tag === 'SortBy'
  }
  isWindowDef(): this is NodePath<'WindowDef'> {
    return this.tag === 'WindowDef'
  }
  isRangeSubselect(): this is NodePath<'RangeSubselect'> {
    return this.tag === 'RangeSubselect'
  }
  isRangeFunction(): this is NodePath<'RangeFunction'> {
    return this.tag === 'RangeFunction'
  }
  isRangeTableFunc(): this is NodePath<'RangeTableFunc'> {
    return this.tag === 'RangeTableFunc'
  }
  isRangeTableFuncCol(): this is NodePath<'RangeTableFuncCol'> {
    return this.tag === 'RangeTableFuncCol'
  }
  isRangeTableSample(): this is NodePath<'RangeTableSample'> {
    return this.tag === 'RangeTableSample'
  }
  isColumnDef(): this is NodePath<'ColumnDef'> {
    return this.tag === 'ColumnDef'
  }
  isTableLikeClause(): this is NodePath<'TableLikeClause'> {
    return this.tag === 'TableLikeClause'
  }
  isIndexElem(): this is NodePath<'IndexElem'> {
    return this.tag === 'IndexElem'
  }
  isDefElem(): this is NodePath<'DefElem'> {
    return this.tag === 'DefElem'
  }
  isLockingClause(): this is NodePath<'LockingClause'> {
    return this.tag === 'LockingClause'
  }
  isXmlSerialize(): this is NodePath<'XmlSerialize'> {
    return this.tag === 'XmlSerialize'
  }
  isPartitionElem(): this is NodePath<'PartitionElem'> {
    return this.tag === 'PartitionElem'
  }
  isPartitionRangeDatum(): this is NodePath<'PartitionRangeDatum'> {
    return this.tag === 'PartitionRangeDatum'
  }
  isPartitionCmd(): this is NodePath<'PartitionCmd'> {
    return this.tag === 'PartitionCmd'
  }
  isGroupingSet(): this is NodePath<'GroupingSet'> {
    return this.tag === 'GroupingSet'
  }
  isCommonTableExpr(): this is NodePath<'CommonTableExpr'> {
    return this.tag === 'CommonTableExpr'
  }
  isMergeWhenClause(): this is NodePath<'MergeWhenClause'> {
    return this.tag === 'MergeWhenClause'
  }
  isTriggerTransition(): this is NodePath<'TriggerTransition'> {
    return this.tag === 'TriggerTransition'
  }
  isJsonKeyValue(): this is NodePath<'JsonKeyValue'> {
    return this.tag === 'JsonKeyValue'
  }
  isJsonObjectConstructor(): this is NodePath<'JsonObjectConstructor'> {
    return this.tag === 'JsonObjectConstructor'
  }
  isJsonArrayConstructor(): this is NodePath<'JsonArrayConstructor'> {
    return this.tag === 'JsonArrayConstructor'
  }
  isJsonArrayQueryConstructor(): this is NodePath<'JsonArrayQueryConstructor'> {
    return this.tag === 'JsonArrayQueryConstructor'
  }
  isJsonObjectAgg(): this is NodePath<'JsonObjectAgg'> {
    return this.tag === 'JsonObjectAgg'
  }
  isJsonArrayAgg(): this is NodePath<'JsonArrayAgg'> {
    return this.tag === 'JsonArrayAgg'
  }
  isInsertStmt(): this is NodePath<'InsertStmt'> {
    return this.tag === 'InsertStmt'
  }
  isDeleteStmt(): this is NodePath<'DeleteStmt'> {
    return this.tag === 'DeleteStmt'
  }
  isUpdateStmt(): this is NodePath<'UpdateStmt'> {
    return this.tag === 'UpdateStmt'
  }
  isMergeStmt(): this is NodePath<'MergeStmt'> {
    return this.tag === 'MergeStmt'
  }
  isSelectStmt(): this is NodePath<'SelectStmt'> {
    return this.tag === 'SelectStmt'
  }
  isReturnStmt(): this is NodePath<'ReturnStmt'> {
    return this.tag === 'ReturnStmt'
  }
  isCreateSchemaStmt(): this is NodePath<'CreateSchemaStmt'> {
    return this.tag === 'CreateSchemaStmt'
  }
  isAlterTableStmt(): this is NodePath<'AlterTableStmt'> {
    return this.tag === 'AlterTableStmt'
  }
  isReplicaIdentityStmt(): this is NodePath<'ReplicaIdentityStmt'> {
    return this.tag === 'ReplicaIdentityStmt'
  }
  isAlterTableCmd(): this is NodePath<'AlterTableCmd'> {
    return this.tag === 'AlterTableCmd'
  }
  isAlterDomainStmt(): this is NodePath<'AlterDomainStmt'> {
    return this.tag === 'AlterDomainStmt'
  }
  isGrantStmt(): this is NodePath<'GrantStmt'> {
    return this.tag === 'GrantStmt'
  }
  isObjectWithArgs(): this is NodePath<'ObjectWithArgs'> {
    return this.tag === 'ObjectWithArgs'
  }
  isAccessPriv(): this is NodePath<'AccessPriv'> {
    return this.tag === 'AccessPriv'
  }
  isGrantRoleStmt(): this is NodePath<'GrantRoleStmt'> {
    return this.tag === 'GrantRoleStmt'
  }
  isAlterDefaultPrivilegesStmt(): this is NodePath<'AlterDefaultPrivilegesStmt'> {
    return this.tag === 'AlterDefaultPrivilegesStmt'
  }
  isCopyStmt(): this is NodePath<'CopyStmt'> {
    return this.tag === 'CopyStmt'
  }
  isVariableSetStmt(): this is NodePath<'VariableSetStmt'> {
    return this.tag === 'VariableSetStmt'
  }
  isVariableShowStmt(): this is NodePath<'VariableShowStmt'> {
    return this.tag === 'VariableShowStmt'
  }
  isCreateStmt(): this is NodePath<'CreateStmt'> {
    return this.tag === 'CreateStmt'
  }
  isConstraint(): this is NodePath<'Constraint'> {
    return this.tag === 'Constraint'
  }
  isCreateTableSpaceStmt(): this is NodePath<'CreateTableSpaceStmt'> {
    return this.tag === 'CreateTableSpaceStmt'
  }
  isDropTableSpaceStmt(): this is NodePath<'DropTableSpaceStmt'> {
    return this.tag === 'DropTableSpaceStmt'
  }
  isAlterTableSpaceOptionsStmt(): this is NodePath<'AlterTableSpaceOptionsStmt'> {
    return this.tag === 'AlterTableSpaceOptionsStmt'
  }
  isAlterTableMoveAllStmt(): this is NodePath<'AlterTableMoveAllStmt'> {
    return this.tag === 'AlterTableMoveAllStmt'
  }
  isCreateExtensionStmt(): this is NodePath<'CreateExtensionStmt'> {
    return this.tag === 'CreateExtensionStmt'
  }
  isAlterExtensionStmt(): this is NodePath<'AlterExtensionStmt'> {
    return this.tag === 'AlterExtensionStmt'
  }
  isAlterExtensionContentsStmt(): this is NodePath<'AlterExtensionContentsStmt'> {
    return this.tag === 'AlterExtensionContentsStmt'
  }
  isCreateFdwStmt(): this is NodePath<'CreateFdwStmt'> {
    return this.tag === 'CreateFdwStmt'
  }
  isAlterFdwStmt(): this is NodePath<'AlterFdwStmt'> {
    return this.tag === 'AlterFdwStmt'
  }
  isCreateForeignServerStmt(): this is NodePath<'CreateForeignServerStmt'> {
    return this.tag === 'CreateForeignServerStmt'
  }
  isAlterForeignServerStmt(): this is NodePath<'AlterForeignServerStmt'> {
    return this.tag === 'AlterForeignServerStmt'
  }
  isCreateForeignTableStmt(): this is NodePath<'CreateForeignTableStmt'> {
    return this.tag === 'CreateForeignTableStmt'
  }
  isCreateUserMappingStmt(): this is NodePath<'CreateUserMappingStmt'> {
    return this.tag === 'CreateUserMappingStmt'
  }
  isAlterUserMappingStmt(): this is NodePath<'AlterUserMappingStmt'> {
    return this.tag === 'AlterUserMappingStmt'
  }
  isDropUserMappingStmt(): this is NodePath<'DropUserMappingStmt'> {
    return this.tag === 'DropUserMappingStmt'
  }
  isImportForeignSchemaStmt(): this is NodePath<'ImportForeignSchemaStmt'> {
    return this.tag === 'ImportForeignSchemaStmt'
  }
  isCreatePolicyStmt(): this is NodePath<'CreatePolicyStmt'> {
    return this.tag === 'CreatePolicyStmt'
  }
  isAlterPolicyStmt(): this is NodePath<'AlterPolicyStmt'> {
    return this.tag === 'AlterPolicyStmt'
  }
  isCreateAmStmt(): this is NodePath<'CreateAmStmt'> {
    return this.tag === 'CreateAmStmt'
  }
  isCreateTrigStmt(): this is NodePath<'CreateTrigStmt'> {
    return this.tag === 'CreateTrigStmt'
  }
  isCreateEventTrigStmt(): this is NodePath<'CreateEventTrigStmt'> {
    return this.tag === 'CreateEventTrigStmt'
  }
  isAlterEventTrigStmt(): this is NodePath<'AlterEventTrigStmt'> {
    return this.tag === 'AlterEventTrigStmt'
  }
  isCreatePLangStmt(): this is NodePath<'CreatePLangStmt'> {
    return this.tag === 'CreatePLangStmt'
  }
  isCreateRoleStmt(): this is NodePath<'CreateRoleStmt'> {
    return this.tag === 'CreateRoleStmt'
  }
  isAlterRoleStmt(): this is NodePath<'AlterRoleStmt'> {
    return this.tag === 'AlterRoleStmt'
  }
  isDropRoleStmt(): this is NodePath<'DropRoleStmt'> {
    return this.tag === 'DropRoleStmt'
  }
  isCreateSeqStmt(): this is NodePath<'CreateSeqStmt'> {
    return this.tag === 'CreateSeqStmt'
  }
  isAlterSeqStmt(): this is NodePath<'AlterSeqStmt'> {
    return this.tag === 'AlterSeqStmt'
  }
  isDefineStmt(): this is NodePath<'DefineStmt'> {
    return this.tag === 'DefineStmt'
  }
  isCreateDomainStmt(): this is NodePath<'CreateDomainStmt'> {
    return this.tag === 'CreateDomainStmt'
  }
  isCreateOpClassStmt(): this is NodePath<'CreateOpClassStmt'> {
    return this.tag === 'CreateOpClassStmt'
  }
  isCreateOpClassItem(): this is NodePath<'CreateOpClassItem'> {
    return this.tag === 'CreateOpClassItem'
  }
  isCreateOpFamilyStmt(): this is NodePath<'CreateOpFamilyStmt'> {
    return this.tag === 'CreateOpFamilyStmt'
  }
  isAlterOpFamilyStmt(): this is NodePath<'AlterOpFamilyStmt'> {
    return this.tag === 'AlterOpFamilyStmt'
  }
  isDropStmt(): this is NodePath<'DropStmt'> {
    return this.tag === 'DropStmt'
  }
  isTruncateStmt(): this is NodePath<'TruncateStmt'> {
    return this.tag === 'TruncateStmt'
  }
  isCommentStmt(): this is NodePath<'CommentStmt'> {
    return this.tag === 'CommentStmt'
  }
  isSecLabelStmt(): this is NodePath<'SecLabelStmt'> {
    return this.tag === 'SecLabelStmt'
  }
  isDeclareCursorStmt(): this is NodePath<'DeclareCursorStmt'> {
    return this.tag === 'DeclareCursorStmt'
  }
  isClosePortalStmt(): this is NodePath<'ClosePortalStmt'> {
    return this.tag === 'ClosePortalStmt'
  }
  isFetchStmt(): this is NodePath<'FetchStmt'> {
    return this.tag === 'FetchStmt'
  }
  isIndexStmt(): this is NodePath<'IndexStmt'> {
    return this.tag === 'IndexStmt'
  }
  isCreateStatsStmt(): this is NodePath<'CreateStatsStmt'> {
    return this.tag === 'CreateStatsStmt'
  }
  isStatsElem(): this is NodePath<'StatsElem'> {
    return this.tag === 'StatsElem'
  }
  isAlterStatsStmt(): this is NodePath<'AlterStatsStmt'> {
    return this.tag === 'AlterStatsStmt'
  }
  isCreateFunctionStmt(): this is NodePath<'CreateFunctionStmt'> {
    return this.tag === 'CreateFunctionStmt'
  }
  isFunctionParameter(): this is NodePath<'FunctionParameter'> {
    return this.tag === 'FunctionParameter'
  }
  isAlterFunctionStmt(): this is NodePath<'AlterFunctionStmt'> {
    return this.tag === 'AlterFunctionStmt'
  }
  isDoStmt(): this is NodePath<'DoStmt'> {
    return this.tag === 'DoStmt'
  }
  isCallStmt(): this is NodePath<'CallStmt'> {
    return this.tag === 'CallStmt'
  }
  isRenameStmt(): this is NodePath<'RenameStmt'> {
    return this.tag === 'RenameStmt'
  }
  isAlterObjectSchemaStmt(): this is NodePath<'AlterObjectSchemaStmt'> {
    return this.tag === 'AlterObjectSchemaStmt'
  }
  isAlterOwnerStmt(): this is NodePath<'AlterOwnerStmt'> {
    return this.tag === 'AlterOwnerStmt'
  }
  isAlterOperatorStmt(): this is NodePath<'AlterOperatorStmt'> {
    return this.tag === 'AlterOperatorStmt'
  }
  isAlterTypeStmt(): this is NodePath<'AlterTypeStmt'> {
    return this.tag === 'AlterTypeStmt'
  }
  isRuleStmt(): this is NodePath<'RuleStmt'> {
    return this.tag === 'RuleStmt'
  }
  isNotifyStmt(): this is NodePath<'NotifyStmt'> {
    return this.tag === 'NotifyStmt'
  }
  isTransactionStmt(): this is NodePath<'TransactionStmt'> {
    return this.tag === 'TransactionStmt'
  }
  isCompositeTypeStmt(): this is NodePath<'CompositeTypeStmt'> {
    return this.tag === 'CompositeTypeStmt'
  }
  isCreateEnumStmt(): this is NodePath<'CreateEnumStmt'> {
    return this.tag === 'CreateEnumStmt'
  }
  isCreateRangeStmt(): this is NodePath<'CreateRangeStmt'> {
    return this.tag === 'CreateRangeStmt'
  }
  isAlterEnumStmt(): this is NodePath<'AlterEnumStmt'> {
    return this.tag === 'AlterEnumStmt'
  }
  isViewStmt(): this is NodePath<'ViewStmt'> {
    return this.tag === 'ViewStmt'
  }
  isLoadStmt(): this is NodePath<'LoadStmt'> {
    return this.tag === 'LoadStmt'
  }
  isDropdbStmt(): this is NodePath<'DropdbStmt'> {
    return this.tag === 'DropdbStmt'
  }
  isClusterStmt(): this is NodePath<'ClusterStmt'> {
    return this.tag === 'ClusterStmt'
  }
  isVacuumStmt(): this is NodePath<'VacuumStmt'> {
    return this.tag === 'VacuumStmt'
  }
  isVacuumRelation(): this is NodePath<'VacuumRelation'> {
    return this.tag === 'VacuumRelation'
  }
  isExplainStmt(): this is NodePath<'ExplainStmt'> {
    return this.tag === 'ExplainStmt'
  }
  isCreateTableAsStmt(): this is NodePath<'CreateTableAsStmt'> {
    return this.tag === 'CreateTableAsStmt'
  }
  isRefreshMatViewStmt(): this is NodePath<'RefreshMatViewStmt'> {
    return this.tag === 'RefreshMatViewStmt'
  }
  isCheckPointStmt(): this is NodePath<'CheckPointStmt'> {
    return this.tag === 'CheckPointStmt'
  }
  isDiscardStmt(): this is NodePath<'DiscardStmt'> {
    return this.tag === 'DiscardStmt'
  }
  isConstraintsSetStmt(): this is NodePath<'ConstraintsSetStmt'> {
    return this.tag === 'ConstraintsSetStmt'
  }
  isReindexStmt(): this is NodePath<'ReindexStmt'> {
    return this.tag === 'ReindexStmt'
  }
  isCreateConversionStmt(): this is NodePath<'CreateConversionStmt'> {
    return this.tag === 'CreateConversionStmt'
  }
  isCreateCastStmt(): this is NodePath<'CreateCastStmt'> {
    return this.tag === 'CreateCastStmt'
  }
  isCreateTransformStmt(): this is NodePath<'CreateTransformStmt'> {
    return this.tag === 'CreateTransformStmt'
  }
  isPrepareStmt(): this is NodePath<'PrepareStmt'> {
    return this.tag === 'PrepareStmt'
  }
  isExecuteStmt(): this is NodePath<'ExecuteStmt'> {
    return this.tag === 'ExecuteStmt'
  }
  isDeallocateStmt(): this is NodePath<'DeallocateStmt'> {
    return this.tag === 'DeallocateStmt'
  }
  isDropOwnedStmt(): this is NodePath<'DropOwnedStmt'> {
    return this.tag === 'DropOwnedStmt'
  }
  isReassignOwnedStmt(): this is NodePath<'ReassignOwnedStmt'> {
    return this.tag === 'ReassignOwnedStmt'
  }
  isAlterTSDictionaryStmt(): this is NodePath<'AlterTSDictionaryStmt'> {
    return this.tag === 'AlterTSDictionaryStmt'
  }
  isAlterTSConfigurationStmt(): this is NodePath<'AlterTSConfigurationStmt'> {
    return this.tag === 'AlterTSConfigurationStmt'
  }
  isPublicationObjSpec(): this is NodePath<'PublicationObjSpec'> {
    return this.tag === 'PublicationObjSpec'
  }
  isCreatePublicationStmt(): this is NodePath<'CreatePublicationStmt'> {
    return this.tag === 'CreatePublicationStmt'
  }
  isAlterPublicationStmt(): this is NodePath<'AlterPublicationStmt'> {
    return this.tag === 'AlterPublicationStmt'
  }
  isCreateSubscriptionStmt(): this is NodePath<'CreateSubscriptionStmt'> {
    return this.tag === 'CreateSubscriptionStmt'
  }
  isAlterSubscriptionStmt(): this is NodePath<'AlterSubscriptionStmt'> {
    return this.tag === 'AlterSubscriptionStmt'
  }
  isDropSubscriptionStmt(): this is NodePath<'DropSubscriptionStmt'> {
    return this.tag === 'DropSubscriptionStmt'
  }
  isInteger(): this is NodePath<'Integer'> {
    return this.tag === 'Integer'
  }
  isFloat(): this is NodePath<'Float'> {
    return this.tag === 'Float'
  }
  isBoolean(): this is NodePath<'Boolean'> {
    return this.tag === 'Boolean'
  }
  isString(): this is NodePath<'String'> {
    return this.tag === 'String'
  }
}
