export const typeMappings: Record<string, string> = {
  void: "void",
  bool: "boolean",
  bits32: "number",
  char: "string",
  "char*": "string",
  double: "number",
  float4: "number",
  long: "number",
  int: "number",
  int16: "number",
  int32: "number",
  uint16: "number",
  uint32: "number",
  uint64: "number",
  "unsigned int": "number",
  "signed int": "number",
  NameData: "string",
  Node: "Node",
  "[]Node": "Node[]",
  RelFileNumber: "number",
  ParallelVacuumState: "any",

  // Overrides
  List: "any[]",
  "Query.cteList": "CommonTableExpr[]",
  "Query.rtable": "RangeTblEntry[]",
  "Query.rteperminfos": "RTEPermissionInfo[]",
  "Query.mergeActionList": "MergeAction[]",
  "Query.targetList": "TargetEntry[]",
  "Query.returningList": "TargetEntry[]",
  "Query.groupClause": "SortGroupClause[]",
  "Query.groupingSets": "GroupingSet[]",
  "Query.windowClause": "WindowClause[]",
  "Query.distinctClause": "SortGroupClause[]",
  "Query.sortClause": "SortGroupClause[]",
  "Query.rowMarks": "RowMarkClause[]",
  "Query.constraintDeps": "Oid[]",
  "Query.withCheckOptions": "WithCheckOption[]",
  "LockingClause.lockedRels": "RangeVar[] | null",
  "PartitionElem.collation": "String[]",
  "TypeName.names": "String[]",
  "ColumnRef.fields": "(String | A_Star)[]",
}
